name: "🙏 Question"
description: Ask a question
title: "[Question]: "
labels: ["type/question", "triage-needed"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure to [search for existing issues](https://github.com/InternRobotics/InternUtopia/issues) before filing a new one!

  - type: textarea
    attributes:
      label: Question
      description: Describe your question in detail.
    validations:
      required: true
